### ISSUE TITLE
Where do you place this plugin?

### ISSUE THREAD

**Issue by ns-1m** [cyberpython/gedit3-webkitview-plugin#1]
Hi,

I am using gedit 3.2 in Mac OS X. I place this plugin in the plugin folder. It was not appearing in the preferences -> plugins tab.

Where do you place this plugin? And how do you activate it.

No instruction is posted how to install this plugin.

**Comment by cyberpython** [comment]
You have to place webkitview.plugin, webkitview.py and gedit-webkitview.svg in ~/.local/share/gedit/plugins (keep in mind though that this plugin is more of an example on how to write a simple plugin and not intended to be used).
